import { Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { RpgErrorState, RpgSkeleton } from "@/components/feedback/RemoteState";
import { queries } from "@/shared/api/queries";

export function SupplementReferencePanel({ characterId }: { characterId: string }) {
	const reference = useQuery(queries.supplementReference(characterId));
	if (reference.isPending) return <RpgSkeleton />;
	if (reference.error) return <RpgErrorState error={reference.error} retry={() => void reference.refetch()} />;
	if (!reference.data.supplementId) return <p className="rounded-2xl bg-(--panel) p-6 text-sm text-(--muted)">Ative um suplemento na campanha ou nesta ficha para consultar suas regras.</p>;
	return <section className="space-y-8" aria-label="Referência do suplemento"><header className="border-b border-(--edge)/60 pb-5"><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-(--accent)">Sobrevivendo ao Horror</p><h3 className="mt-2 font-serif text-3xl">Regras e ameaças</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-(--muted)">As regras mostradas aqui alteram a ficha e foram ativadas para esta personagem.</p></header><div className="grid gap-8 xl:grid-cols-[minmax(0,1fr)_20rem]"><div className="space-y-3"><h4 className="font-serif text-2xl">Regras em jogo</h4>{reference.data.rules.length === 0 ? <p className="text-sm text-(--muted)">Nenhuma regra liberada.</p> : reference.data.rules.map((rule) => <details key={rule.id} className="group rounded-2xl border border-(--edge)/55 bg-(--panel) p-4"><summary className="cursor-pointer list-none"><span className="font-mono text-[10px] uppercase tracking-wider text-(--accent)">Página {rule.sourcePage} {rule.optional ? "· opcional" : ""}</span><span className="mt-1 block font-serif text-xl">{rule.name}</span></summary><p className="mt-4 whitespace-pre-wrap border-t border-(--edge)/50 pt-4 text-sm leading-7 text-(--muted)">{rule.text}</p></details>)}</div><aside className="space-y-3"><h4 className="font-serif text-2xl">Ameaças</h4>{reference.data.threats.length === 0 ? <p className="text-sm text-(--muted)">Nenhuma ameaça liberada para esta campanha.</p> : reference.data.threats.map((threat) => <Link key={threat.id} to="/bestiary/$threatId" params={{ threatId: threat.id }} className="block rounded-2xl border border-(--edge)/55 bg-(--panel) p-4 transition-colors hover:border-(--accent) focus-visible:outline-2 focus-visible:outline-(--accent)"><span className="font-mono text-[10px] uppercase tracking-wider text-(--accent)">Página {threat.sourcePage}</span><span className="mt-1 block font-serif text-xl">{threat.name}</span><span className="mt-2 line-clamp-3 block text-xs leading-5 text-(--muted)">{threat.description}</span></Link>)}</aside></div></section>;
}
